### ISSUE TITLE
[Bug] App crash on animation loading

### ISSUE THREAD

**Issue by WhinsonDoseCodeing** [KaruzoHikari/Wii-Phone#23]
When i try to load in the mobile os. it starts loading the animations i have, than it crashes. i have no idea why, culd be a memory overflow or somethin. i wuld gladly use this app as my phone os but i cant since it crashes wich makes me sad.
[device: Xsaomi Redmi note 10 s]

**Comment by KaruzoHikari** [comment]
Hey there!

It's indeed a memory overflow, your phone is loading many photos, videos, GIFs and/or audios at once, which can make the app run out of memory and crash.
That's why the app runs worse the more animations you use (it does NOT matter how many you have downloaded, it only matters how many are getting loaded), and specially with heavy animations (long videos/GIFs, high resolution images...).
I encourage every animation creator on the Hub to use *image* animations, as they will take way less time and space to load (and in general, they look better when animated).

This is a very tricky thing to fix. The animations assets definitely need to be loaded, or I wouldn't be able to display them otherwise.
I could add a setting to -not- load the banners until they open, but then the first time you open each banner, it'd hang for a few seconds until the animation loads. Perhaps a "safe mode" automatically activating the setting if the app crashed would be ideal here, but then the people using it as a launcher would crash anyway the first time.

I'll give it some thoughts. In the meantime, I'm open to any suggestions (preferably on the Discord server). Thanks for your patience!

**Comment by KaruzoHikari** [comment]
Hopefully fixed in v3.2, with all the changes to the way the app handles its assets!
