### ISSUE TITLE
MP3 files not working

### ISSUE THREAD

**Issue by LuckRiiStar190** [KaruzoHikari/Wii-Phone#25]
When I try to use an MP3 file in the animation editor, no audio plays.

**Comment by KaruzoHikari** [comment]
Hey there!
I've seen some people having issues adding audio to animations, because while the extension of their file was "`.mp3`", the file wasn't actually an mp3.
I suggest checking this post first, and reopen if it still doesn't work. Thanks!
https://discord.com/channels/927324051159019530/927650512394911774/968895874115723315
